=== magenta-aps/db-preservation-toolkit/dbptk-core/src/test/resources/siarddk/AVID.SA.18001.2/Tables/table2/table2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema0/table2.xsd" targetNamespace="http://www.sa.dk/xmlns/siard/1.0/schema0/table2.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="row" type="rowType" maxOccurs="unbounded" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="rowType">
    <xs:sequence>
      <xs:element name="c1" minOccurs="1" type="xs:string" nillable="false" />
      <xs:element name="c2" minOccurs="1" type="xs:string" nillable="true" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="NonEmptyString">
    <xs:restriction base="xs:string">
      <xs:pattern value="(.|\n|\r)+" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== magenta-aps/db-preservation-toolkit/dbptk-core/src/test/resources/siarddk/AVID.TST.4000.1/Tables/table2/table2.xml
<?xml version="1.0" encoding="utf-8"?>
<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema2/table2.xsd table2.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema2/table2.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <row>
    <c1>BO</c1>
    <c2>Bornholms\u0020Amt</c2>
  </row>
  <row>
    <c1>DK</c1>
    <c2>Danmark</c2>
  </row>
  <row>
    <c1>FR</c1>
    <c2>Frederiksborg\u0020Amt</c2>
  </row>
  <row>
    <c1>FY</c1>
    <c2>Fyns\u0020Amt</c2>
  </row>
  <row>
    <c1>K\u00D8</c1>
    <c2>K\u00F8benhavns\u0020Amt</c2>
  </row>
  <row>
    <c1>NO</c1>
    <c2>Nordjyllands\u0020Amt</c2>
  </row>
  <row>
    <c1>RB</c1>
    <c2>Ribe\u0020Amt</c2>
  </row>
  <row>
    <c1>RK</c1>
    <c2>Ringk\u00F8bing\u0020Amt</c2>
  </row>
  <row>
    <c1>RO</c1>
    <c2>Roskilde\u0020Amt</c2>
  </row>
  <row>
    <c1>ST</c1>
    <c2>Storstr\u00F8ms\u0020Amt</c2>
  </row>
  <row>
    <c1>S\u00D8</c1>
    <c2>S\u00F8nderjyllands\u0020Amt</c2>
  </row>
  <row>
    <c1>VE</c1>
    <c2>Vejle\u0020Amt</c2>
  </row>
  <row>
    <c1>VI</c1>
    <c2>Viborg\u0020Amt</c2>
  </row>
  <row>
    <c1>VS</c1>
    <c2>Vestsj\u00E6llands\u0020Amt</c2>
  </row>
  <row>
    <c1>\u00C5R</c1>
    <c2>\u00C5rhus\u0020Amt</c2>
  </row>
</table>
