=== magenta-aps/db-preservation-toolkit/dbptk-core/src/test/resources/siarddk/AVID.HEX.1000.1/Tables/table1/table1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd" targetNamespace="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified"><xs:element name="table"><xs:complexType><xs:sequence><xs:element minOccurs="0" maxOccurs="unbounded" name="row" type="rowType" /></xs:sequence></xs:complexType></xs:element><xs:complexType name="rowType"><xs:sequence><xs:element name="c1" type="xs:string" /><xs:element name="c2" type="xs:string" /><xs:element name="c3" type="xs:string" /><xs:element name="c4" type="xs:string" /><xs:element name="c5" type="xs:decimal" /><xs:element name="c6" type="xs:integer" nillable="true" /><xs:element name="c7" type="xs:integer" /><xs:element name="c8" type="xs:decimal" nillable="true" /><xs:element name="c9" type="xs:decimal" nillable="true" /><xs:element name="c10" type="xs:decimal" nillable="true" /><xs:element name="c11" type="xs:string" /><xs:element name="c12" type="xs:string" /><xs:element name="c13" type="xs:string" nillable="true" /><xs:element name="c14" type="xs:string" /><xs:element name="c15" type="xs:hexBinary" nillable="true" /></xs:sequence></xs:complexType></xs:schema>

=== magenta-aps/db-preservation-toolkit/dbptk-core/src/test/resources/siarddk/AVID.HEX.2000.1/Tables/table1/table1.xml
<?xml version="1.0" encoding="utf-8"?>
<table xsi:schemaLocation="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd table1.xsd" xmlns="http://www.sa.dk/xmlns/siard/1.0/schema1/table1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <row>
    <c1>BMU</c1>
    <c2>Bermuda</c2>
    <c3>North\u0020America</c3>
    <c4>North\u0020America</c4>
    <c5>53.0</c5>
    <c6 xsi:nil="true"/>
    <c7>65000</c7>
    <c8>76.9</c8>
    <c9>2328.00</c9>
    <c10>2190.00</c10>
    <c11>Bermuda</c11>
    <c12>Dependent\u0020Territory\u0020of\u0020the\u0020UK</c12>
    <c13>Elisabeth\u0020II</c13>
    <c14>BM</c14>
    <c15>Bermuda</c15>
  </row>
  <row>
    <c1>BTN</c1>
    <c2>Bhutan</c2>
    <c3>Asia</c3>
    <c4>Southern\u0020and\u0020Central\u0020Asia</c4>
    <c5>47000.0</c5>
    <c6>1910</c6>
    <c7>2124000</c7>
    <c8>52.4</c8>
    <c9>372.00</c9>
    <c10>383.00</c10>
    <c11>Druk-Yul</c11>
    <c12>Monarchy</c12>
    <c13>Jigme\u0020Singye\u0020Wangchuk</c13>
    <c14>BT</c14>
    <c15>Bhutan</c15>
  </row>
  <row>
    <c1>BOL</c1>
    <c2>Bolivia</c2>
    <c3>South\u0020America</c3>
    <c4>South\u0020America</c4>
    <c5>1098581.0</c5>
    <c6>1825</c6>
    <c7>8329000</c7>
    <c8>63.7</c8>
    <c9>8571.00</c9>
    <c10>7967.00</c10>
    <c11>Bolivia</c11>
    <c12>Republic</c12>
    <c13>Hugo\u0020B\u00E1nzer\u0020Su\u00E1rez</c13>
    <c14>BO</c14>
    <c15>Bolivia</c15>
  </row>
  <row>
    <c1>BIH</c1>
    <c2>Bosnia\u0020and\u0020Herzegovina</c2>
    <c3>Europe</c3>
    <c4>Southern\u0020Europe</c4>
    <c5>51197.0</c5>
    <c6>1992</c6>
    <c7>3972000</c7>
    <c8>71.5</c8>
    <c9>2841.00</c9>
    <c10 xsi:nil="true"/>
    <c11>Bosna\u0020i\u0020Hercegovina</c11>
    <c12>Federal\u0020Republic</c12>
    <c13>Ante\u0020Jelavic</c13>
    <c14>BA</c14>
    <c15>Bosnia\u0020and\u0020Herzegovina</c15>
  </row>
  <row>
    <c1>BWA</c1>
    <c2>Botswana</c2>
    <c3>Africa</c3>
    <c4>Southern\u0020Africa</c4>
    <c5>581730.0</c5>
    <c6>1966</c6>
    <c7>1622000</c7>
    <c8>39.3</c8>
    <c9>4834.00</c9>
    <c10>4935.00</c10>
    <c11>Botswana</c11>
    <c12>Republic</c12>
    <c13>Festus\u0020G.\u0020Mogae</c13>
    <c14>BW</c14>
    <c15>Botswana</c15>
  </row>
  <row>
    <c1>BRA</c1>
    <c2>Brazil</c2>
    <c3>South\u0020America</c3>
    <c4>South\u0020America</c4>
    <c5>8547403.0</c5>
    <c6>1822</c6>
    <c7>170115000</c7>
    <c8>62.9</c8>
    <c9>776739.00</c9>
    <c10>804108.00</c10>
    <c11>Brasil</c11>
    <c12>Federal\u0020Republic</c12>
    <c13>Fernando\u0020Henrique\u0020Cardoso</c13>
    <c14>BR</c14>
    <c15>Brazil</c15>
  </row>
  <row>
    <c1>GBR</c1>
    <c2>United\u0020Kingdom</c2>
    <c3>Europe</c3>
    <c4>British\u0020Islands</c4>
    <c5>242900.0</c5>
    <c6>1066</c6>
    <c7>59623400</c7>
    <c8>77.7</c8>
    <c9>1378330.00</c9>
    <c10>1296830.00</c10>
    <c11>United\u0020Kingdom</c11>
    <c12>Constitutional\u0020Monarchy</c12>
    <c13>Elisabeth\u0020II</c13>
    <c14>GB</c14>
    <c15>United\u0020Kingdom</c15>
  </row>
  <row>
    <c1>VGB</c1>
    <c2>Virgin\u0020Islands,\u0020British</c2>
    <c3>North\u0020America</c3>
    <c4>Caribbean</c4>
    <c5>151.0</c5>
    <c6 xsi:nil="true"/>
    <c7>21000</c7>
    <c8>75.4</c8>
    <c9>612.00</c9>
    <c10>573.00</c10>
    <c11>British\u0020Virgin\u0020Islands</c11>
    <c12>Dependent\u0020Territory\u0020of\u0020the\u0020UK</c12>
    <c13>Elisabeth\u0020II</c13>
    <c14>VG</c14>
    <c15>Virgin\u0020Islands,\u0020British</c15>
  </row>
  <row>
    <c1>BRN</c1>
    <c2>Brunei</c2>
    <c3>Asia</c3>
    <c4>Southeast\u0020Asia</c4>
    <c5>5765.0</c5>
    <c6>1984</c6>
    <c7>328000</c7>
    <c8>73.6</c8>
    <c9>11705.00</c9>
    <c10>12460.00</c10>
    <c11>Brunei\u0020Darussalam</c11>
    <c12>Monarchy\u0020(Sultanate)</c12>
    <c13>Haji\u0020Hassan\u0020al-Bolkiah</c13>
    <c14>BN</c14>
    <c15>Brunei</c15>
  </row>
  <row>
    <c1>BGR</c1>
    <c2>Bulgaria</c2>
    <c3>Europe</c3>
    <c4>Eastern\u0020Europe</c4>
    <c5>110994.0</c5>
    <c6>1908</c6>
    <c7>8190900</c7>
    <c8>70.9</c8>
    <c9>12178.00</c9>
    <c10>10169.00</c10>
    <c11>Balgarija</c11>
    <c12>Republic</c12>
    <c13>Petar\u0020Stojanov</c13>
    <c14>BG</c14>
    <c15>Bulgaria</c15>
  </row>
</table>
